//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elden_Ring_Param_Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elden_Ring_Param_Randomizer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All done! 的本地化字符串。
        /// </summary>
        internal static string All_done {
            get {
                return ResourceManager.GetString("All done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arcane:  的本地化字符串。
        /// </summary>
        internal static string Arcane {
            get {
                return ResourceManager.GetString("Arcane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrypting Regulation 的本地化字符串。
        /// </summary>
        internal static string Decrypting_Regulation {
            get {
                return ResourceManager.GetString("Decrypting Regulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dexterity 的本地化字符串。
        /// </summary>
        internal static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elden Ring Param Randomizer 的本地化字符串。
        /// </summary>
        internal static string Elden_Ring_Param_Randomizer {
            get {
                return ResourceManager.GetString("Elden Ring Param Randomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EquipParamWeapon(Requirement) 的本地化字符串。
        /// </summary>
        internal static string EquipParamWeapon_Requirement_ {
            get {
                return ResourceManager.GetString("EquipParamWeapon(Requirement)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EquipParamWeapon(Weight) 的本地化字符串。
        /// </summary>
        internal static string EquipParamWeapon_Weight_ {
            get {
                return ResourceManager.GetString("EquipParamWeapon(Weight)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting Params 的本地化字符串。
        /// </summary>
        internal static string Exporting_Params {
            get {
                return ResourceManager.GetString("Exporting Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Faith:  的本地化字符串。
        /// </summary>
        internal static string Faith {
            get {
                return ResourceManager.GetString("Faith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Regulation.bin 的本地化字符串。
        /// </summary>
        internal static string File_Selected {
            get {
                return ResourceManager.GetString("File Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished! 的本地化字符串。
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handling Params 的本地化字符串。
        /// </summary>
        internal static string Handling_Params {
            get {
                return ResourceManager.GetString("Handling Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intelligence:  的本地化字符串。
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading ParamDefs 的本地化字符串。
        /// </summary>
        internal static string Loading_ParamDefs {
            get {
                return ResourceManager.GetString("Loading ParamDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max weight(0.1~1000.0) 的本地化字符串。
        /// </summary>
        internal static string Max_weight_0_1_1000_0_ {
            get {
                return ResourceManager.GetString("Max weight(0.1~1000.0)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifying Params 的本地化字符串。
        /// </summary>
        internal static string Modifying_Params {
            get {
                return ResourceManager.GetString("Modifying Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Setting! 的本地化字符串。
        /// </summary>
        internal static string No_Setting {
            get {
                return ResourceManager.GetString("No Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No File Selected! 的本地化字符串。
        /// </summary>
        internal static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please put oo2core_6_win64.dll into randomizer folder. 的本地化字符串。
        /// </summary>
        internal static string NoOodleFoundException {
            get {
                return ResourceManager.GetString("NoOodleFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Param Selected! 的本地化字符串。
        /// </summary>
        internal static string NoParamSelected {
            get {
                return ResourceManager.GetString("NoParamSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose regulation.bin 的本地化字符串。
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Randomization Finished 的本地化字符串。
        /// </summary>
        internal static string Randomization_Finished {
            get {
                return ResourceManager.GetString("Randomization Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Randomize 的本地化字符串。
        /// </summary>
        internal static string Randomize {
            get {
                return ResourceManager.GetString("Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Click CheckBox to Setting 的本地化字符串。
        /// </summary>
        internal static string Right_Click_CheckBox_to_Setting {
            get {
                return ResourceManager.GetString("Right Click CheckBox to Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Modifying the Regulation.bin directly used by Elden Ring is ill-advised, as it&apos;s possible you may be banned.
        ///It&apos;s highly recommended you instead use Mod Engine 2 and modify a copy of Regulation.bin.
        ///
        ///Are you sure you want to load the Regulation.bin you selected? 的本地化字符串。
        /// </summary>
        internal static string SameFolder {
            get {
                return ResourceManager.GetString("SameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strength:  的本地化字符串。
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Talk Param(Message) 的本地化字符串。
        /// </summary>
        internal static string Talk_Param_Message_ {
            get {
                return ResourceManager.GetString("Talk Param(Message)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.1.0 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for regulation 的本地化字符串。
        /// </summary>
        internal static string Waiting_for_regulation {
            get {
                return ResourceManager.GetString("Waiting for regulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon Requirement Setting 的本地化字符串。
        /// </summary>
        internal static string Weapon_Requirement_Setting {
            get {
                return ResourceManager.GetString("Weapon Requirement Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon Weight Setting 的本地化字符串。
        /// </summary>
        internal static string Weapon_Weight_Setting {
            get {
                return ResourceManager.GetString("Weapon Weight Setting", resourceCulture);
            }
        }
    }
}
