//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elden_Ring_Param_Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elden_Ring_Param_Randomizer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        internal static string All_done {
            get {
                return ResourceManager.GetString("All done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcane: .
        /// </summary>
        internal static string Arcane {
            get {
                return ResourceManager.GetString("Arcane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting Regulation.
        /// </summary>
        internal static string Decrypting_Regulation {
            get {
                return ResourceManager.GetString("Decrypting Regulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        internal static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elden Ring Param Randomizer.
        /// </summary>
        internal static string Elden_Ring_Param_Randomizer {
            get {
                return ResourceManager.GetString("Elden Ring Param Randomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquipParamWeapon(Requirement).
        /// </summary>
        internal static string EquipParamWeapon_Requirement_ {
            get {
                return ResourceManager.GetString("EquipParamWeapon(Requirement)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquipParamWeapon(Scaling).
        /// </summary>
        internal static string EquipParamWeapon_Scaling_ {
            get {
                return ResourceManager.GetString("EquipParamWeapon(Scaling)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquipParamWeapon(Weight).
        /// </summary>
        internal static string EquipParamWeapon_Weight_ {
            get {
                return ResourceManager.GetString("EquipParamWeapon(Weight)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Params.
        /// </summary>
        internal static string Exporting_Params {
            get {
                return ResourceManager.GetString("Exporting Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faith: .
        /// </summary>
        internal static string Faith {
            get {
                return ResourceManager.GetString("Faith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Regulation.bin.
        /// </summary>
        internal static string File_Selected {
            get {
                return ResourceManager.GetString("File Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling Params.
        /// </summary>
        internal static string Handling_Params {
            get {
                return ResourceManager.GetString("Handling Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence: .
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ParamDefs.
        /// </summary>
        internal static string Loading_ParamDefs {
            get {
                return ResourceManager.GetString("Loading ParamDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max weight(0.1~1000.0).
        /// </summary>
        internal static string Max_weight_0_1_1000_0_ {
            get {
                return ResourceManager.GetString("Max weight(0.1~1000.0)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying Params.
        /// </summary>
        internal static string Modifying_Params {
            get {
                return ResourceManager.GetString("Modifying Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Setting!.
        /// </summary>
        internal static string No_Setting {
            get {
                return ResourceManager.GetString("No Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected!.
        /// </summary>
        internal static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please put oo2core_6_win64.dll into randomizer folder..
        /// </summary>
        internal static string NoOodleFoundException {
            get {
                return ResourceManager.GetString("NoOodleFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Param Selected!.
        /// </summary>
        internal static string NoParamSelected {
            get {
                return ResourceManager.GetString("NoParamSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose regulation.bin.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomization Finished.
        /// </summary>
        internal static string Randomization_Finished {
            get {
                return ResourceManager.GetString("Randomization Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        internal static string Randomize {
            get {
                return ResourceManager.GetString("Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click CheckBox to Setting.
        /// </summary>
        internal static string Right_Click_CheckBox_to_Setting {
            get {
                return ResourceManager.GetString("Right Click CheckBox to Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Modifying the Regulation.bin directly used by Elden Ring is ill-advised, as it&apos;s possible you may be banned.
        ///It&apos;s highly recommended you instead use Mod Engine 2 and modify a copy of Regulation.bin.
        ///
        ///Are you sure you want to load the Regulation.bin you selected?.
        /// </summary>
        internal static string SameFolder {
            get {
                return ResourceManager.GetString("SameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength: .
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk Param(Message).
        /// </summary>
        internal static string Talk_Param_Message_ {
            get {
                return ResourceManager.GetString("Talk Param(Message)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heavier the weapon, the smaller the chance of a random hit..
        /// </summary>
        internal static string The_heavier_the_weapon__the_smaller_the_chance_of_a_random_hit_ {
            get {
                return ResourceManager.GetString("The heavier the weapon, the smaller the chance of a random hit.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0.1.2-Untested.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for regulation.
        /// </summary>
        internal static string Waiting_for_regulation {
            get {
                return ResourceManager.GetString("Waiting for regulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Requirement Setting.
        /// </summary>
        internal static string Weapon_Requirement_Setting {
            get {
                return ResourceManager.GetString("Weapon Requirement Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Scaling Setting.
        /// </summary>
        internal static string Weapon_Scaling_Setting {
            get {
                return ResourceManager.GetString("Weapon Scaling Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Weight Setting.
        /// </summary>
        internal static string Weapon_Weight_Setting {
            get {
                return ResourceManager.GetString("Weapon Weight Setting", resourceCulture);
            }
        }
    }
}
